# Generated by Django 4.2.7 on 2023-12-13 22:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppRefugio', '0004_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor_entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de entrada'),
        ),
        migrations.AddField(
            model_name='libro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros_imagenes/'),
        ),
    ]
